=begin
#Stateset

#This is the Stateset One API based on The OpenAPI Specification. # Introduction This API definition is intended to to be a good starting point for describing your API in [OpenAPI/Swagger format](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md). # OpenAPI Specification The goal of The OpenAPI Specification is to define a standard, language-agnostic interface to REST APIs which allows both humans and computers to discover and understand the capabilities of the service without access to source code, documentation, or through network traffic inspection. When properly defined via OpenAPI, a consumer can  understand and interact with the remote service with a minimal amount of implementation logic. Similar to what interfaces have done for lower-level programming, OpenAPI removes the guesswork in calling the service. 

The version of the OpenAPI document: 1.0.0
Contact: developers@stateset.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.6.0

=end

require 'date'
require 'time'

module OpenapiClient
  class ModelReturn
    attr_accessor :id

    # The status of the return.
    attr_accessor :status

    # The order ID associated with the return.
    attr_accessor :order_id

    # The return merchandise authorization number.
    attr_accessor :rma

    # The tracking number of the returned item.
    attr_accessor :tracking_number

    # A description of the return.
    attr_accessor :description

    # The email address of the customer who initiated the return.
    attr_accessor :customer_email

    # The unique identifier of the Zendesk ticket associated with the return.
    attr_accessor :zendesk_number

    # Any action required to process the return.
    attr_accessor :action_needed

    # The reason for the return.
    attr_accessor :issue

    # The string the order was placed.
    attr_accessor :order_string

    # The string the order was shipped.
    attr_accessor :shipped_string

    # The string the return was requested.
    attr_accessor :requested_string

    # The name of the employee who entered the return into the system.
    attr_accessor :entered_by

    # The unique identifier of the customer who initiated the return.
    attr_accessor :customer_id

    # The amount of the return.
    attr_accessor :amount

    # The condition of the returned item.
    attr_accessor :reported_condition

    # The amount of tax refunded.
    attr_accessor :tax_refunded

    # The total amount refunded.
    attr_accessor :total_refunded

    # The string the return was created.
    attr_accessor :created_string

    # The category of the reason for the return.
    attr_accessor :reason_category

    # The flat rate shipping amount.
    attr_accessor :flat_rate_shipping

    # The string the return was refunded.
    attr_accessor :refunded_string

    # The string the return was received at the warehouse.
    attr_accessor :warehouse_received_string

    # The string the condition of the return was verified at the warehouse.
    attr_accessor :warehouse_condition_string

    # The status of the return in FedEx.
    attr_accessor :fedex_status

    # The serial number of the returned item.
    attr_accessor :scanned_serial_number

    # Whether or not the serial number matches the order.
    attr_accessor :match

    # The country of the customer who initiated the return.
    attr_accessor :country

    # The serial number of the returned item.
    attr_accessor :serial_number

    # The condition of the returned item.
    attr_accessor :condition

    # Whether or not the order was refunded.
    attr_accessor :order_refunded

    # The workflow ID associated with the return.
    attr_accessor :workflow_id

    # The unique identifier of the SSO user who initiated the return.
    attr_accessor :sso_id

    # The normalized email address of the customer who initiated the return.
    attr_accessor :customer_email_normalized

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'id' => :'id',
        :'status' => :'status',
        :'order_id' => :'order_id',
        :'rma' => :'rma',
        :'tracking_number' => :'tracking_number',
        :'description' => :'description',
        :'customer_email' => :'customer_email',
        :'zendesk_number' => :'zendesk_number',
        :'action_needed' => :'action_needed',
        :'issue' => :'issue',
        :'order_string' => :'order_string',
        :'shipped_string' => :'shipped_string',
        :'requested_string' => :'requested_string',
        :'entered_by' => :'enteredBy',
        :'customer_id' => :'customer_id',
        :'amount' => :'amount',
        :'reported_condition' => :'reported_condition',
        :'tax_refunded' => :'tax_refunded',
        :'total_refunded' => :'total_refunded',
        :'created_string' => :'created_string',
        :'reason_category' => :'reason_category',
        :'flat_rate_shipping' => :'flat_rate_shipping',
        :'refunded_string' => :'refunded_string',
        :'warehouse_received_string' => :'warehouse_received_string',
        :'warehouse_condition_string' => :'warehouse_condition_string',
        :'fedex_status' => :'fedex_status',
        :'scanned_serial_number' => :'scanned_serial_number',
        :'match' => :'match',
        :'country' => :'country',
        :'serial_number' => :'serial_number',
        :'condition' => :'condition',
        :'order_refunded' => :'order_refunded',
        :'workflow_id' => :'workflow_id',
        :'sso_id' => :'sso_id',
        :'customer_email_normalized' => :'customer_email_normalized'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'id' => :'String',
        :'status' => :'String',
        :'order_id' => :'String',
        :'rma' => :'String',
        :'tracking_number' => :'String',
        :'description' => :'String',
        :'customer_email' => :'String',
        :'zendesk_number' => :'String',
        :'action_needed' => :'String',
        :'issue' => :'String',
        :'order_string' => :'String',
        :'shipped_string' => :'String',
        :'requested_string' => :'String',
        :'entered_by' => :'String',
        :'customer_id' => :'String',
        :'amount' => :'String',
        :'reported_condition' => :'String',
        :'tax_refunded' => :'String',
        :'total_refunded' => :'String',
        :'created_string' => :'String',
        :'reason_category' => :'String',
        :'flat_rate_shipping' => :'Integer',
        :'refunded_string' => :'String',
        :'warehouse_received_string' => :'String',
        :'warehouse_condition_string' => :'String',
        :'fedex_status' => :'String',
        :'scanned_serial_number' => :'String',
        :'match' => :'String',
        :'country' => :'String',
        :'serial_number' => :'String',
        :'condition' => :'String',
        :'order_refunded' => :'Boolean',
        :'workflow_id' => :'String',
        :'sso_id' => :'String',
        :'customer_email_normalized' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `OpenapiClient::ModelReturn` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `OpenapiClient::ModelReturn`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      end

      if attributes.key?(:'status')
        self.status = attributes[:'status']
      end

      if attributes.key?(:'order_id')
        self.order_id = attributes[:'order_id']
      end

      if attributes.key?(:'rma')
        self.rma = attributes[:'rma']
      end

      if attributes.key?(:'tracking_number')
        self.tracking_number = attributes[:'tracking_number']
      end

      if attributes.key?(:'description')
        self.description = attributes[:'description']
      end

      if attributes.key?(:'customer_email')
        self.customer_email = attributes[:'customer_email']
      end

      if attributes.key?(:'zendesk_number')
        self.zendesk_number = attributes[:'zendesk_number']
      end

      if attributes.key?(:'action_needed')
        self.action_needed = attributes[:'action_needed']
      end

      if attributes.key?(:'issue')
        self.issue = attributes[:'issue']
      end

      if attributes.key?(:'order_string')
        self.order_string = attributes[:'order_string']
      end

      if attributes.key?(:'shipped_string')
        self.shipped_string = attributes[:'shipped_string']
      end

      if attributes.key?(:'requested_string')
        self.requested_string = attributes[:'requested_string']
      end

      if attributes.key?(:'entered_by')
        self.entered_by = attributes[:'entered_by']
      end

      if attributes.key?(:'customer_id')
        self.customer_id = attributes[:'customer_id']
      end

      if attributes.key?(:'amount')
        self.amount = attributes[:'amount']
      end

      if attributes.key?(:'reported_condition')
        self.reported_condition = attributes[:'reported_condition']
      end

      if attributes.key?(:'tax_refunded')
        self.tax_refunded = attributes[:'tax_refunded']
      end

      if attributes.key?(:'total_refunded')
        self.total_refunded = attributes[:'total_refunded']
      end

      if attributes.key?(:'created_string')
        self.created_string = attributes[:'created_string']
      else
        self.created_string = 'now()'
      end

      if attributes.key?(:'reason_category')
        self.reason_category = attributes[:'reason_category']
      end

      if attributes.key?(:'flat_rate_shipping')
        self.flat_rate_shipping = attributes[:'flat_rate_shipping']
      end

      if attributes.key?(:'refunded_string')
        self.refunded_string = attributes[:'refunded_string']
      end

      if attributes.key?(:'warehouse_received_string')
        self.warehouse_received_string = attributes[:'warehouse_received_string']
      end

      if attributes.key?(:'warehouse_condition_string')
        self.warehouse_condition_string = attributes[:'warehouse_condition_string']
      end

      if attributes.key?(:'fedex_status')
        self.fedex_status = attributes[:'fedex_status']
      end

      if attributes.key?(:'scanned_serial_number')
        self.scanned_serial_number = attributes[:'scanned_serial_number']
      end

      if attributes.key?(:'match')
        self.match = attributes[:'match']
      end

      if attributes.key?(:'country')
        self.country = attributes[:'country']
      end

      if attributes.key?(:'serial_number')
        self.serial_number = attributes[:'serial_number']
      end

      if attributes.key?(:'condition')
        self.condition = attributes[:'condition']
      end

      if attributes.key?(:'order_refunded')
        self.order_refunded = attributes[:'order_refunded']
      else
        self.order_refunded = false
      end

      if attributes.key?(:'workflow_id')
        self.workflow_id = attributes[:'workflow_id']
      end

      if attributes.key?(:'sso_id')
        self.sso_id = attributes[:'sso_id']
      end

      if attributes.key?(:'customer_email_normalized')
        self.customer_email_normalized = attributes[:'customer_email_normalized']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          status == o.status &&
          order_id == o.order_id &&
          rma == o.rma &&
          tracking_number == o.tracking_number &&
          description == o.description &&
          customer_email == o.customer_email &&
          zendesk_number == o.zendesk_number &&
          action_needed == o.action_needed &&
          issue == o.issue &&
          order_string == o.order_string &&
          shipped_string == o.shipped_string &&
          requested_string == o.requested_string &&
          entered_by == o.entered_by &&
          customer_id == o.customer_id &&
          amount == o.amount &&
          reported_condition == o.reported_condition &&
          tax_refunded == o.tax_refunded &&
          total_refunded == o.total_refunded &&
          created_string == o.created_string &&
          reason_category == o.reason_category &&
          flat_rate_shipping == o.flat_rate_shipping &&
          refunded_string == o.refunded_string &&
          warehouse_received_string == o.warehouse_received_string &&
          warehouse_condition_string == o.warehouse_condition_string &&
          fedex_status == o.fedex_status &&
          scanned_serial_number == o.scanned_serial_number &&
          match == o.match &&
          country == o.country &&
          serial_number == o.serial_number &&
          condition == o.condition &&
          order_refunded == o.order_refunded &&
          workflow_id == o.workflow_id &&
          sso_id == o.sso_id &&
          customer_email_normalized == o.customer_email_normalized
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [id, status, order_id, rma, tracking_number, description, customer_email, zendesk_number, action_needed, issue, order_string, shipped_string, requested_string, entered_by, customer_id, amount, reported_condition, tax_refunded, total_refunded, created_string, reason_category, flat_rate_shipping, refunded_string, warehouse_received_string, warehouse_condition_string, fedex_status, scanned_serial_number, match, country, serial_number, condition, order_refunded, workflow_id, sso_id, customer_email_normalized].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      new.build_from_hash(attributes)
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      self.class.openapi_types.each_pair do |key, type|
        if attributes[self.class.attribute_map[key]].nil? && self.class.openapi_nullable.include?(key)
          self.send("#{key}=", nil)
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = OpenapiClient.const_get(type)
        klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
