=begin
#Stateset

#This is the Stateset One API based on The OpenAPI Specification. # Introduction This API definition is intended to to be a good starting point for describing your API in [OpenAPI/Swagger format](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md). # OpenAPI Specification The goal of The OpenAPI Specification is to define a standard, language-agnostic interface to REST APIs which allows both humans and computers to discover and understand the capabilities of the service without access to source code, documentation, or through network traffic inspection. When properly defined via OpenAPI, a consumer can  understand and interact with the remote service with a minimal amount of implementation logic. Similar to what interfaces have done for lower-level programming, OpenAPI removes the guesswork in calling the service. 

The version of the OpenAPI document: 1.0.0
Contact: developers@stateset.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.6.0

=end

require 'date'
require 'time'

module OpenapiClient
  class Warranty
    attr_accessor :id

    attr_accessor :warranty_number

    attr_accessor :warranty_name

    attr_accessor :warranty_type

    attr_accessor :created_date

    attr_accessor :expiration_date

    attr_accessor :order_id

    attr_accessor :description

    attr_accessor :status

    attr_accessor :issue

    attr_accessor :tracking_number

    attr_accessor :action_needed

    attr_accessor :customer_email

    attr_accessor :rma

    attr_accessor :zendesk_number

    attr_accessor :entered_by

    attr_accessor :order_date

    attr_accessor :shipped_date

    attr_accessor :requested_date

    attr_accessor :condition

    attr_accessor :reported_condition

    attr_accessor :amount

    attr_accessor :tax_refunded

    attr_accessor :total_refunded

    attr_accessor :created_date

    attr_accessor :serial_number

    attr_accessor :reason_category

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'id' => :'id',
        :'warranty_number' => :'warrantyNumber',
        :'warranty_name' => :'warrantyName',
        :'warranty_type' => :'warrantyType',
        :'created_date' => :'createdDate',
        :'expiration_date' => :'expirationDate',
        :'order_id' => :'order_id',
        :'description' => :'description',
        :'status' => :'status',
        :'issue' => :'issue',
        :'tracking_number' => :'tracking_number',
        :'action_needed' => :'action_needed',
        :'customer_email' => :'customerEmail',
        :'rma' => :'rma',
        :'zendesk_number' => :'zendesk_number',
        :'entered_by' => :'enteredBy',
        :'order_date' => :'order_date',
        :'shipped_date' => :'shipped_date',
        :'requested_date' => :'requested_date',
        :'condition' => :'condition',
        :'reported_condition' => :'reported_condition',
        :'amount' => :'amount',
        :'tax_refunded' => :'tax_refunded',
        :'total_refunded' => :'total_refunded',
        :'created_date' => :'created_date',
        :'serial_number' => :'serial_number',
        :'reason_category' => :'reason_category'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'id' => :'String',
        :'warranty_number' => :'String',
        :'warranty_name' => :'String',
        :'warranty_type' => :'String',
        :'created_date' => :'Time',
        :'expiration_date' => :'Time',
        :'order_id' => :'String',
        :'description' => :'String',
        :'status' => :'String',
        :'issue' => :'String',
        :'tracking_number' => :'String',
        :'action_needed' => :'String',
        :'customer_email' => :'String',
        :'rma' => :'String',
        :'zendesk_number' => :'String',
        :'entered_by' => :'String',
        :'order_date' => :'Time',
        :'shipped_date' => :'Time',
        :'requested_date' => :'Time',
        :'condition' => :'String',
        :'reported_condition' => :'String',
        :'amount' => :'String',
        :'tax_refunded' => :'String',
        :'total_refunded' => :'String',
        :'created_date' => :'Time',
        :'serial_number' => :'String',
        :'reason_category' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `OpenapiClient::Warranty` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `OpenapiClient::Warranty`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      end

      if attributes.key?(:'warranty_number')
        self.warranty_number = attributes[:'warranty_number']
      end

      if attributes.key?(:'warranty_name')
        self.warranty_name = attributes[:'warranty_name']
      end

      if attributes.key?(:'warranty_type')
        self.warranty_type = attributes[:'warranty_type']
      end

      if attributes.key?(:'created_date')
        self.created_date = attributes[:'created_date']
      end

      if attributes.key?(:'expiration_date')
        self.expiration_date = attributes[:'expiration_date']
      end

      if attributes.key?(:'order_id')
        self.order_id = attributes[:'order_id']
      end

      if attributes.key?(:'description')
        self.description = attributes[:'description']
      end

      if attributes.key?(:'status')
        self.status = attributes[:'status']
      end

      if attributes.key?(:'issue')
        self.issue = attributes[:'issue']
      end

      if attributes.key?(:'tracking_number')
        self.tracking_number = attributes[:'tracking_number']
      end

      if attributes.key?(:'action_needed')
        self.action_needed = attributes[:'action_needed']
      end

      if attributes.key?(:'customer_email')
        self.customer_email = attributes[:'customer_email']
      end

      if attributes.key?(:'rma')
        self.rma = attributes[:'rma']
      end

      if attributes.key?(:'zendesk_number')
        self.zendesk_number = attributes[:'zendesk_number']
      end

      if attributes.key?(:'entered_by')
        self.entered_by = attributes[:'entered_by']
      end

      if attributes.key?(:'order_date')
        self.order_date = attributes[:'order_date']
      end

      if attributes.key?(:'shipped_date')
        self.shipped_date = attributes[:'shipped_date']
      end

      if attributes.key?(:'requested_date')
        self.requested_date = attributes[:'requested_date']
      end

      if attributes.key?(:'condition')
        self.condition = attributes[:'condition']
      end

      if attributes.key?(:'reported_condition')
        self.reported_condition = attributes[:'reported_condition']
      end

      if attributes.key?(:'amount')
        self.amount = attributes[:'amount']
      end

      if attributes.key?(:'tax_refunded')
        self.tax_refunded = attributes[:'tax_refunded']
      end

      if attributes.key?(:'total_refunded')
        self.total_refunded = attributes[:'total_refunded']
      end

      if attributes.key?(:'created_date')
        self.created_date = attributes[:'created_date']
      end

      if attributes.key?(:'serial_number')
        self.serial_number = attributes[:'serial_number']
      end

      if attributes.key?(:'reason_category')
        self.reason_category = attributes[:'reason_category']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          warranty_number == o.warranty_number &&
          warranty_name == o.warranty_name &&
          warranty_type == o.warranty_type &&
          created_date == o.created_date &&
          expiration_date == o.expiration_date &&
          order_id == o.order_id &&
          description == o.description &&
          status == o.status &&
          issue == o.issue &&
          tracking_number == o.tracking_number &&
          action_needed == o.action_needed &&
          customer_email == o.customer_email &&
          rma == o.rma &&
          zendesk_number == o.zendesk_number &&
          entered_by == o.entered_by &&
          order_date == o.order_date &&
          shipped_date == o.shipped_date &&
          requested_date == o.requested_date &&
          condition == o.condition &&
          reported_condition == o.reported_condition &&
          amount == o.amount &&
          tax_refunded == o.tax_refunded &&
          total_refunded == o.total_refunded &&
          created_date == o.created_date &&
          serial_number == o.serial_number &&
          reason_category == o.reason_category
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [id, warranty_number, warranty_name, warranty_type, created_date, expiration_date, order_id, description, status, issue, tracking_number, action_needed, customer_email, rma, zendesk_number, entered_by, order_date, shipped_date, requested_date, condition, reported_condition, amount, tax_refunded, total_refunded, created_date, serial_number, reason_category].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      new.build_from_hash(attributes)
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      self.class.openapi_types.each_pair do |key, type|
        if attributes[self.class.attribute_map[key]].nil? && self.class.openapi_nullable.include?(key)
          self.send("#{key}=", nil)
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = OpenapiClient.const_get(type)
        klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
